### ISSUE TITLE
Missing jvm.dll

### ISSUE THREAD

**Issue by vertigo220** [ykon/w10wheel.net#8]
I was working on a project about a week ago where I was killing w10wheel, replacing the files, and restarting it (automating updates), and after doing this several times, it suddenly wouldn't launch anymore, giving me an error that jvm.dll was missing. I had to download and install the JRE to get it working again. What's really strange about this is that it's not even included with w10wheel. I have no idea what exactly happened to break it, and it's certainly a unique situation, but I wonder if this file should be included since it's required, to prevent the need to download and install JRE just for it if there's ever an issue.

**Comment by Chouffy** [comment]
Are you using the "legacy" [W10Wheel](https://github.com/ykon/w10wheel) which is based on Java, or this version [W10Wheel.net](https://github.com/ykon/w10wheel.net) which is based on .NET?
For the former version (which is this repo where you opened this issue), you just need .NET (see main page) and not JVM :)

**Comment by ykon** [comment]
The exewrap is still out of date, so updating it may fix it. 
https://translate.google.com/translate?sl=ja&tl=en&u=https://exewrap.osdn.jp/history.html

The Java version is not as functionally different as legacy, but the .NET version has a higher priority.
Recently, I've been busy changing jobs, so I haven't been able to maintain this.

**Comment by vertigo220** [comment]
Good call. I was setting up an auto-check for and download and update new version and accidentally grabbed the legacy version. Closing this issue, and thanks!
